### ISSUE TITLE
Logging unknown format warning

### ISSUE THREAD

**Issue by cdobbyn** [logzio/fluent-bit-logzio-output#23]
Right now the [timestamp lookup](https://github.com/logzio/fluent-bit-logzio-output/blob/master/output/out_logzio.go#L309) is confusing and spams the logs. Please change this so that:
1. the warning is a proper warning log (not a fmt.Print) and it follows fluentbit logging level
2. it outputs something useful (this should be configurable)
  - at least show me the timestamp in question
  - or the entire log
  - allow me to squelch this entirely

![image](https://github.com/logzio/fluent-bit-logzio-output/assets/8264498/0bf8c921-252b-4ed0-8d6a-99c08b20b8bc)

**Comment by ralongit** [comment]
Hello @cdobbyn ,
Thank you for reporting this. It should be resolved in the latest version(0.4.0) of our plugin.
